/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DirectImport } from './routes/direct'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DirectRoute = DirectImport.update({
  id: '/direct',
  path: '/direct',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/direct': {
      id: '/direct'
      path: '/direct'
      fullPath: '/direct'
      preLoaderRoute: typeof DirectImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/direct': typeof DirectRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/direct': typeof DirectRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/direct': typeof DirectRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/direct'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/direct'
  id: '__root__' | '/' | '/direct'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectRoute: typeof DirectRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectRoute: DirectRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/direct"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/direct": {
      "filePath": "direct.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
